name: aggrepay_flutter
description: The Aggrepay flutter SDK allows you to integrate Aggrepay payment gateway into your flutter application.
version: 0.0.2
homepage: null

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:
 
  plugin:
    platforms:
      android:
        package: com.example.aggrepay_flutter
        pluginClass: AggrepayFlutterPlugin
      ios:
        pluginClass: AggrepayFlutterPlugin
  